# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import service_pb2 as service__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TradingServiceStub(object):
    """TODO: Convert stuff like side, asset_class, etc. to enums.

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PlaceStockOrder = channel.unary_unary(
                '/tradr.TradingService/PlaceStockOrder',
                request_serializer=service__pb2.PlaceStockOrderRequest.SerializeToString,
                response_deserializer=service__pb2.PlaceOrderResponse.FromString,
                _registered_method=True)
        self.PlaceOptionOrder = channel.unary_unary(
                '/tradr.TradingService/PlaceOptionOrder',
                request_serializer=service__pb2.PlaceOptionOrderRequest.SerializeToString,
                response_deserializer=service__pb2.PlaceOrderResponse.FromString,
                _registered_method=True)
        self.CancelOrder = channel.unary_unary(
                '/tradr.TradingService/CancelOrder',
                request_serializer=service__pb2.CancelOrderRequest.SerializeToString,
                response_deserializer=service__pb2.CancelOrderResponse.FromString,
                _registered_method=True)
        self.ModifyOrder = channel.unary_unary(
                '/tradr.TradingService/ModifyOrder',
                request_serializer=service__pb2.ModifyOrderRequest.SerializeToString,
                response_deserializer=service__pb2.ModifyOrderResponse.FromString,
                _registered_method=True)
        self.GetOrder = channel.unary_unary(
                '/tradr.TradingService/GetOrder',
                request_serializer=service__pb2.GetOrderRequest.SerializeToString,
                response_deserializer=service__pb2.OrderRecord.FromString,
                _registered_method=True)
        self.ListOrders = channel.unary_unary(
                '/tradr.TradingService/ListOrders',
                request_serializer=service__pb2.ListOrdersRequest.SerializeToString,
                response_deserializer=service__pb2.ListOrdersResponse.FromString,
                _registered_method=True)
        self.ListFills = channel.unary_unary(
                '/tradr.TradingService/ListFills',
                request_serializer=service__pb2.ListFillsRequest.SerializeToString,
                response_deserializer=service__pb2.ListFillsResponse.FromString,
                _registered_method=True)
        self.GetPositions = channel.unary_unary(
                '/tradr.TradingService/GetPositions',
                request_serializer=service__pb2.GetPositionsRequest.SerializeToString,
                response_deserializer=service__pb2.GetPositionsResponse.FromString,
                _registered_method=True)
        self.GetAccountValues = channel.unary_unary(
                '/tradr.TradingService/GetAccountValues',
                request_serializer=service__pb2.GetAccountValuesRequest.SerializeToString,
                response_deserializer=service__pb2.GetAccountValuesResponse.FromString,
                _registered_method=True)


class TradingServiceServicer(object):
    """TODO: Convert stuff like side, asset_class, etc. to enums.

    """

    def PlaceStockOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PlaceOptionOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ModifyOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListOrders(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListFills(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPositions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAccountValues(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TradingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PlaceStockOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.PlaceStockOrder,
                    request_deserializer=service__pb2.PlaceStockOrderRequest.FromString,
                    response_serializer=service__pb2.PlaceOrderResponse.SerializeToString,
            ),
            'PlaceOptionOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.PlaceOptionOrder,
                    request_deserializer=service__pb2.PlaceOptionOrderRequest.FromString,
                    response_serializer=service__pb2.PlaceOrderResponse.SerializeToString,
            ),
            'CancelOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelOrder,
                    request_deserializer=service__pb2.CancelOrderRequest.FromString,
                    response_serializer=service__pb2.CancelOrderResponse.SerializeToString,
            ),
            'ModifyOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.ModifyOrder,
                    request_deserializer=service__pb2.ModifyOrderRequest.FromString,
                    response_serializer=service__pb2.ModifyOrderResponse.SerializeToString,
            ),
            'GetOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrder,
                    request_deserializer=service__pb2.GetOrderRequest.FromString,
                    response_serializer=service__pb2.OrderRecord.SerializeToString,
            ),
            'ListOrders': grpc.unary_unary_rpc_method_handler(
                    servicer.ListOrders,
                    request_deserializer=service__pb2.ListOrdersRequest.FromString,
                    response_serializer=service__pb2.ListOrdersResponse.SerializeToString,
            ),
            'ListFills': grpc.unary_unary_rpc_method_handler(
                    servicer.ListFills,
                    request_deserializer=service__pb2.ListFillsRequest.FromString,
                    response_serializer=service__pb2.ListFillsResponse.SerializeToString,
            ),
            'GetPositions': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPositions,
                    request_deserializer=service__pb2.GetPositionsRequest.FromString,
                    response_serializer=service__pb2.GetPositionsResponse.SerializeToString,
            ),
            'GetAccountValues': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAccountValues,
                    request_deserializer=service__pb2.GetAccountValuesRequest.FromString,
                    response_serializer=service__pb2.GetAccountValuesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tradr.TradingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tradr.TradingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TradingService(object):
    """TODO: Convert stuff like side, asset_class, etc. to enums.

    """

    @staticmethod
    def PlaceStockOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tradr.TradingService/PlaceStockOrder',
            service__pb2.PlaceStockOrderRequest.SerializeToString,
            service__pb2.PlaceOrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PlaceOptionOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tradr.TradingService/PlaceOptionOrder',
            service__pb2.PlaceOptionOrderRequest.SerializeToString,
            service__pb2.PlaceOrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tradr.TradingService/CancelOrder',
            service__pb2.CancelOrderRequest.SerializeToString,
            service__pb2.CancelOrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ModifyOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tradr.TradingService/ModifyOrder',
            service__pb2.ModifyOrderRequest.SerializeToString,
            service__pb2.ModifyOrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tradr.TradingService/GetOrder',
            service__pb2.GetOrderRequest.SerializeToString,
            service__pb2.OrderRecord.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListOrders(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tradr.TradingService/ListOrders',
            service__pb2.ListOrdersRequest.SerializeToString,
            service__pb2.ListOrdersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListFills(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tradr.TradingService/ListFills',
            service__pb2.ListFillsRequest.SerializeToString,
            service__pb2.ListFillsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPositions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tradr.TradingService/GetPositions',
            service__pb2.GetPositionsRequest.SerializeToString,
            service__pb2.GetPositionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAccountValues(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tradr.TradingService/GetAccountValues',
            service__pb2.GetAccountValuesRequest.SerializeToString,
            service__pb2.GetAccountValuesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
