/**
 * @fileoverview gRPC-Web generated client stub for tradr
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v6.31.1
// source: service.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.tradr = require('./service_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.tradr.TradingServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.tradr.TradingServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.tradr.PlaceStockOrderRequest,
 *   !proto.tradr.PlaceOrderResponse>}
 */
const methodDescriptor_TradingService_PlaceStockOrder = new grpc.web.MethodDescriptor(
  '/tradr.TradingService/PlaceStockOrder',
  grpc.web.MethodType.UNARY,
  proto.tradr.PlaceStockOrderRequest,
  proto.tradr.PlaceOrderResponse,
  /**
   * @param {!proto.tradr.PlaceStockOrderRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.tradr.PlaceOrderResponse.deserializeBinary
);


/**
 * @param {!proto.tradr.PlaceStockOrderRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.tradr.PlaceOrderResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.tradr.PlaceOrderResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.tradr.TradingServiceClient.prototype.placeStockOrder =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/tradr.TradingService/PlaceStockOrder',
      request,
      metadata || {},
      methodDescriptor_TradingService_PlaceStockOrder,
      callback);
};


/**
 * @param {!proto.tradr.PlaceStockOrderRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.tradr.PlaceOrderResponse>}
 *     Promise that resolves to the response
 */
proto.tradr.TradingServicePromiseClient.prototype.placeStockOrder =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/tradr.TradingService/PlaceStockOrder',
      request,
      metadata || {},
      methodDescriptor_TradingService_PlaceStockOrder);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.tradr.PlaceOptionOrderRequest,
 *   !proto.tradr.PlaceOrderResponse>}
 */
const methodDescriptor_TradingService_PlaceOptionOrder = new grpc.web.MethodDescriptor(
  '/tradr.TradingService/PlaceOptionOrder',
  grpc.web.MethodType.UNARY,
  proto.tradr.PlaceOptionOrderRequest,
  proto.tradr.PlaceOrderResponse,
  /**
   * @param {!proto.tradr.PlaceOptionOrderRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.tradr.PlaceOrderResponse.deserializeBinary
);


/**
 * @param {!proto.tradr.PlaceOptionOrderRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.tradr.PlaceOrderResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.tradr.PlaceOrderResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.tradr.TradingServiceClient.prototype.placeOptionOrder =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/tradr.TradingService/PlaceOptionOrder',
      request,
      metadata || {},
      methodDescriptor_TradingService_PlaceOptionOrder,
      callback);
};


/**
 * @param {!proto.tradr.PlaceOptionOrderRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.tradr.PlaceOrderResponse>}
 *     Promise that resolves to the response
 */
proto.tradr.TradingServicePromiseClient.prototype.placeOptionOrder =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/tradr.TradingService/PlaceOptionOrder',
      request,
      metadata || {},
      methodDescriptor_TradingService_PlaceOptionOrder);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.tradr.CancelOrderRequest,
 *   !proto.tradr.CancelOrderResponse>}
 */
const methodDescriptor_TradingService_CancelOrder = new grpc.web.MethodDescriptor(
  '/tradr.TradingService/CancelOrder',
  grpc.web.MethodType.UNARY,
  proto.tradr.CancelOrderRequest,
  proto.tradr.CancelOrderResponse,
  /**
   * @param {!proto.tradr.CancelOrderRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.tradr.CancelOrderResponse.deserializeBinary
);


/**
 * @param {!proto.tradr.CancelOrderRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.tradr.CancelOrderResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.tradr.CancelOrderResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.tradr.TradingServiceClient.prototype.cancelOrder =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/tradr.TradingService/CancelOrder',
      request,
      metadata || {},
      methodDescriptor_TradingService_CancelOrder,
      callback);
};


/**
 * @param {!proto.tradr.CancelOrderRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.tradr.CancelOrderResponse>}
 *     Promise that resolves to the response
 */
proto.tradr.TradingServicePromiseClient.prototype.cancelOrder =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/tradr.TradingService/CancelOrder',
      request,
      metadata || {},
      methodDescriptor_TradingService_CancelOrder);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.tradr.GetOrderRequest,
 *   !proto.tradr.OrderRecord>}
 */
const methodDescriptor_TradingService_GetOrder = new grpc.web.MethodDescriptor(
  '/tradr.TradingService/GetOrder',
  grpc.web.MethodType.UNARY,
  proto.tradr.GetOrderRequest,
  proto.tradr.OrderRecord,
  /**
   * @param {!proto.tradr.GetOrderRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.tradr.OrderRecord.deserializeBinary
);


/**
 * @param {!proto.tradr.GetOrderRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.tradr.OrderRecord)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.tradr.OrderRecord>|undefined}
 *     The XHR Node Readable Stream
 */
proto.tradr.TradingServiceClient.prototype.getOrder =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/tradr.TradingService/GetOrder',
      request,
      metadata || {},
      methodDescriptor_TradingService_GetOrder,
      callback);
};


/**
 * @param {!proto.tradr.GetOrderRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.tradr.OrderRecord>}
 *     Promise that resolves to the response
 */
proto.tradr.TradingServicePromiseClient.prototype.getOrder =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/tradr.TradingService/GetOrder',
      request,
      metadata || {},
      methodDescriptor_TradingService_GetOrder);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.tradr.ListOrdersRequest,
 *   !proto.tradr.ListOrdersResponse>}
 */
const methodDescriptor_TradingService_ListOrders = new grpc.web.MethodDescriptor(
  '/tradr.TradingService/ListOrders',
  grpc.web.MethodType.UNARY,
  proto.tradr.ListOrdersRequest,
  proto.tradr.ListOrdersResponse,
  /**
   * @param {!proto.tradr.ListOrdersRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.tradr.ListOrdersResponse.deserializeBinary
);


/**
 * @param {!proto.tradr.ListOrdersRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.tradr.ListOrdersResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.tradr.ListOrdersResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.tradr.TradingServiceClient.prototype.listOrders =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/tradr.TradingService/ListOrders',
      request,
      metadata || {},
      methodDescriptor_TradingService_ListOrders,
      callback);
};


/**
 * @param {!proto.tradr.ListOrdersRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.tradr.ListOrdersResponse>}
 *     Promise that resolves to the response
 */
proto.tradr.TradingServicePromiseClient.prototype.listOrders =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/tradr.TradingService/ListOrders',
      request,
      metadata || {},
      methodDescriptor_TradingService_ListOrders);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.tradr.ListFillsRequest,
 *   !proto.tradr.ListFillsResponse>}
 */
const methodDescriptor_TradingService_ListFills = new grpc.web.MethodDescriptor(
  '/tradr.TradingService/ListFills',
  grpc.web.MethodType.UNARY,
  proto.tradr.ListFillsRequest,
  proto.tradr.ListFillsResponse,
  /**
   * @param {!proto.tradr.ListFillsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.tradr.ListFillsResponse.deserializeBinary
);


/**
 * @param {!proto.tradr.ListFillsRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.tradr.ListFillsResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.tradr.ListFillsResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.tradr.TradingServiceClient.prototype.listFills =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/tradr.TradingService/ListFills',
      request,
      metadata || {},
      methodDescriptor_TradingService_ListFills,
      callback);
};


/**
 * @param {!proto.tradr.ListFillsRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.tradr.ListFillsResponse>}
 *     Promise that resolves to the response
 */
proto.tradr.TradingServicePromiseClient.prototype.listFills =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/tradr.TradingService/ListFills',
      request,
      metadata || {},
      methodDescriptor_TradingService_ListFills);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.tradr.GetPositionsRequest,
 *   !proto.tradr.GetPositionsResponse>}
 */
const methodDescriptor_TradingService_GetPositions = new grpc.web.MethodDescriptor(
  '/tradr.TradingService/GetPositions',
  grpc.web.MethodType.UNARY,
  proto.tradr.GetPositionsRequest,
  proto.tradr.GetPositionsResponse,
  /**
   * @param {!proto.tradr.GetPositionsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.tradr.GetPositionsResponse.deserializeBinary
);


/**
 * @param {!proto.tradr.GetPositionsRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.tradr.GetPositionsResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.tradr.GetPositionsResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.tradr.TradingServiceClient.prototype.getPositions =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/tradr.TradingService/GetPositions',
      request,
      metadata || {},
      methodDescriptor_TradingService_GetPositions,
      callback);
};


/**
 * @param {!proto.tradr.GetPositionsRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.tradr.GetPositionsResponse>}
 *     Promise that resolves to the response
 */
proto.tradr.TradingServicePromiseClient.prototype.getPositions =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/tradr.TradingService/GetPositions',
      request,
      metadata || {},
      methodDescriptor_TradingService_GetPositions);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.tradr.GetAccountValuesRequest,
 *   !proto.tradr.GetAccountValuesResponse>}
 */
const methodDescriptor_TradingService_GetAccountValues = new grpc.web.MethodDescriptor(
  '/tradr.TradingService/GetAccountValues',
  grpc.web.MethodType.UNARY,
  proto.tradr.GetAccountValuesRequest,
  proto.tradr.GetAccountValuesResponse,
  /**
   * @param {!proto.tradr.GetAccountValuesRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.tradr.GetAccountValuesResponse.deserializeBinary
);


/**
 * @param {!proto.tradr.GetAccountValuesRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.tradr.GetAccountValuesResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.tradr.GetAccountValuesResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.tradr.TradingServiceClient.prototype.getAccountValues =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/tradr.TradingService/GetAccountValues',
      request,
      metadata || {},
      methodDescriptor_TradingService_GetAccountValues,
      callback);
};


/**
 * @param {!proto.tradr.GetAccountValuesRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.tradr.GetAccountValuesResponse>}
 *     Promise that resolves to the response
 */
proto.tradr.TradingServicePromiseClient.prototype.getAccountValues =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/tradr.TradingService/GetAccountValues',
      request,
      metadata || {},
      methodDescriptor_TradingService_GetAccountValues);
};


module.exports = proto.tradr;

